theme: jekyll-theme-slate
title: Antonio León Villares
description: Hi, I'm Antonio. I am currently a DPhil Student @ FLAIR & TVG, University of Oxford.
author: "Antonio León Villares"
email: "your.email@example.com"
url: "https://<your-github-username>.github.io" # replace
baseurl: "" # set if served from repo subpath, otherwise leave empty
paginate: 6
markdown: kramdown
